export const CONTRACT_MANAGEMENT_LOADING = "CONTRACT_MANAGEMENT_LOADING";
export const CONTRACT_MANAGEMENT_SUCCESS = "CONTRACT_MANAGEMENT_SUCCESS";

export const CONTRACT_MANAGEMENT_LIST_LOADING =
  "CONTRACT_MANAGEMENT_LIST_LOADING";
export const CONTRACT_MANAGEMENT_LIST_SUCCESS =
  "CONTRACT_MANAGEMENT_LIST_SUCCESS";