export const DATA_FAMILY_LOADING = "DATA_FAMILY_LOADING";
export const DATA_FAMILY_SUCCESS = "DATA_FAMILY_SUCCESS";

export const DATA_FAMILY_LIST_LOADING = "DATA_FAMILY_LIST_LOADING";
export const DATA_FAMILY_LIST_SUCCESS = "DATA_FAMILY_LIST_SUCCESS";

export const DATA_FAMILY_FILTERED_LIST = "DATA_FAMILY_FILTERED_LIST";

export const DATASET_BY_ID = "DATASET_BY_ID";