export const LICENSE_LOADING = "LICENSE_LOADING";
export const LICENSE_SUCCESS = "LICENSE_SUCCESS";

export const LICENSE_LIST_LOADING = "LICENSE_LIST_LOADING";
export const LICENSE_LIST_SUCCESS = "LICENSE_LIST_SUCCESS";
export const LICENSE_DETAILS = "LICENSE_DETAILS";
export const LICENSE_BY_ID = "LICENSE_BY_ID";