import {
    Col,
    Form,
    Input,
    Radio,
    Row,
    Select,
    Tooltip,
    Upload,
    message,
    Button,
} from "antd";
import { UploadOutlined } from "@ant-design/icons";
//_________ importing AntD components Begin*/
import "antd/dist/antd.css";
import React, { useEffect, useState } from "react";
import { useSelector } from "react-redux";
//_________importing Redux components begin
import { connect } from "react-redux";
//_________importing CSS library begin
import "./NewVendorForm.css";
import countryList from "country-list";

const { Option } = Select;
const { TextArea } = Input;
const URL = "https://";

const NewVendorForm = (props) => {
    const [nameFound, setNameFound] = useState(false);
    const [slashFound, setSlashFound] = useState(false);

    const [longNameFound, setLongNameFound] = useState(false);
    let countryListNew = countryList.getCodeList();
    countryListNew = { GO: "Global", ...countryListNew };

    const entityList = useSelector((state) => state.vendor);
    const options = [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
        { label: "NOT SURE", value: "not sure" },
    ];

    const onChange3 = (e) => { };

    useEffect(() => { }, [props]);

    const handelDuplicateNameCheck = (event) => {
        let entityId = document.getElementById("EntityId");
        props.handleNameCheck(event, entityId.value)
            ? setNameFound(true)
            : setNameFound(false);
    };

    const handleSlash = (event) => {
        event.target.value.includes("/")
            ? setSlashFound(true)
            : setSlashFound(false);
    };

    const handelDuplicateLongNameCheck = (event) => {
        let entityId = document.getElementById("EntityId");
        props.handleLongNameCheck(event, entityId.value)
            ? setLongNameFound(true)
            : setLongNameFound(false);
    };

    const checkValidation = (rule, value) => {
        const RGX = /^[A-Za-z](?!.*?[^\na-z0-9]{2}).*?[a-z0-9]$/gim;
        if (RGX.test(value.trim())) {
            return Promise.resolve("");
        } else {
            const msg =
                value !== "" &&
                "Special characters are not allowed at first and last and also No numeric at the beginning of the Long Name.";
            return Promise.reject(msg);
        }
    };

    return (
        <div>
            <Row gutter={{ xs: 8, sm: 16, md: 24, lg: 32 }}>
                <Col className="gutter-row" span={12}>
                    <Form.Item
                        label={
                            <span>
                                <Tooltip
                                    placement="top"
                                    title="EntityID will be generated by the system after the submission"
                                >
                                    Entity ID
                                </Tooltip>
                            </span>
                        }
                        name="entityId"
                    >
                        <Input
                            placeholder="EntityID will be generated by the system after the submission "
                            name="entityId"
                            readOnly
                            disabled
                            type="text"
                            id="EntityId"
                        />
                    </Form.Item>
                </Col>
                <Col className="gutter-row" span={12}>
                    <Form.Item
                        label="Entity Type"
                        name="entityType"
                        rules={[{ required: true, message: "Entity type is mandatory !" }]}
                    >
                        <Select placeholder="Select entity type" name="entityType">
                            <Option value="External Vendor">External Vendor</Option>
                            <Option value="External Partner">External Partner</Option>
                        </Select>
                    </Form.Item>
                </Col>
                <Col className="gutter-row" span={12}>
                    <Form.Item
                        label={
                            <Tooltip placement="top" title="Long name of the entity">
                                {" "}
                                Long Name
                            </Tooltip>
                        }
                        name="longName"
                        rules={[
                            { required: true, message: "Entity long name is mandatory !" },
                            //{ validator: checkValidation },
                        ]}
                        {...(longNameFound && {
                            hasFeedback: true,
                            help: longNameFound ? "Entity already exists" : "",
                            validateStatus: longNameFound === false ? "success" : "error",
                        })}
                    >
                        <Input
                            placeholder="Enter long name"
                            name="longName"
                            type="text"
                            onBlur={handelDuplicateLongNameCheck}
                        />
                    </Form.Item>
                </Col>

                <Col className="gutter-row" span={12}>
                    <Form.Item
                        className="hello"
                        label="Short Name"
                        name="shortName"
                        rules={[
                            { required: true, message: "Entity short name is mandatory !" },
                        ]}
                        {...(slashFound && {
                            hasFeedback: true,
                            help: slashFound ? "Please Remove '/' from the Short Name" : "",
                            validateStatus: slashFound === false ? "success" : "error",
                        })}
                        {...(nameFound && {
                            hasFeedback: true,
                            help: nameFound ? "Entity already exists" : "",
                            validateStatus: nameFound === false ? "success" : "error",
                        })}
                    >
                        <Input
                            placeholder="Enter short name"
                            name="shortName"
                            type="text"
                            onChange={handleSlash}
                            onBlur={handelDuplicateNameCheck}
                        />
                    </Form.Item>
                </Col>
                <Col className="gutter-row" span={12}>
                    <Form.Item className="hello" label="Status" name="entityStatus">
                        <Input
                            placeholder="auto-generated by system"
                            name="entityStatus"
                            type="text"
                            readOnly
                            disabled
                        />
                    </Form.Item>
                </Col>
                <Col className="gutter-row" span={12}>
                    {/*_______________________VENDOR WEBSITE________________________*/}
                    <Form.Item
                        label={
                            <Tooltip
                                placement="top"
                                title="Website URL of the data publisher"
                            >
                                {" "}
                                Website{" "}
                            </Tooltip>
                        }
                        name="website"
                        rules={[
                            {
                                pattern:
                                    "(https?://(?:www.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9].[^s]{2,}|www.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9].[^s]{2,}|https?://(?:www.|(?!www))[a-zA-Z0-9]+.[^s]{2,}|www.[a-zA-Z0-9]+.[^s]{2,})",
                                message: "Entity a valid website !",
                            },
                        ]}
                    >
                        <Input
                            addonBefore={URL}
                            placeholder={`Enter the Website as ${"www.abc.com"}`}
                            defaultValue={props.website}
                        />
                    </Form.Item>
                </Col>
                <Col className="gutter-row" span={12}>
                    {/*_____________________VENDOR DESCRIPTION__________________________*/}
                    <Form.Item
                        label={
                            <Tooltip placement="top" title="Entity Description">
                                {" "}
                                Description{" "}
                            </Tooltip>
                        }
                        name="entityDescription"
                        rules={[
                            { required: true, message: "Entity description is mandatory !" },
                        ]}
                    >
                        <TextArea
                            rows={4}
                            maxLength={250}
                            showCount
                            placeholder="A description about the entity(Max 250characters)"
                            name="entityDescription"
                        />
                    </Form.Item>
                </Col>
            </Row>

            {/*_______________________ FORM SUBMIT / CANCEL ______________________*/}
        </div>
    );
};

const mapStateToProps = (state, props) => {
    return {
        vendorList: state.vendor && state.vendor.list,
    };
};

export default connect(mapStateToProps)(NewVendorForm);