import React, { useState } from "react";
import { connect } from "react-redux";
import {
  Box,
  Grid,
  InputAdornment,
  Tooltip,
} from "@mui/material";

import { FormField } from "../../../design-system";
import "./NewVendorForm.css";

const URL_PREFIX = "https://";

const websitePattern =
  /^(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})$/;

const NewVendorForm = ({ control, watch, setValue, handleNameCheck, handleLongNameCheck }) => {
  const [nameFound, setNameFound] = useState(false);
  const [slashFound, setSlashFound] = useState(false);
  const [longNameFound, setLongNameFound] = useState(false);

  const handleDuplicateName = (event) => {
    const entityIdInput = document.getElementById("EntityId");
    const entityId = entityIdInput ? entityIdInput.value : undefined;
    setNameFound(!!handleNameCheck(event, entityId));
  };

  const handleSlash = (event) => {
    setSlashFound(event.target.value.includes("/"));
  };

  const handleDuplicateLongName = (event) => {
    const entityIdInput = document.getElementById("EntityId");
    const entityId = entityIdInput ? entityIdInput.value : undefined;
    setLongNameFound(!!handleLongNameCheck(event, entityId));
  };

  return (
    <Box>
      <Grid container spacing={3}>
        <Grid size={{ xs: 12, md: 6 }}>
          <Tooltip
            placement="top"
            title="EntityID will be generated by the system after the submission"
          >
            <span className="field-tooltip-target">
              <FormField
                name="entityId"
                label="Entity ID"
                control={control}
                placeholder="EntityID will be generated by the system after the submission"
                disabled
                inputProps={{ id: "EntityId" }}
              />
            </span>
          </Tooltip>
        </Grid>

        <Grid size={{ xs: 12, md: 6 }}>
          <FormField
            name="entityType"
            label="Entity Type"
            control={control}
            type="select"
            required="Entity type is mandatory !"
            options={[
              { value: "External Vendor", label: "External Vendor" },
              { value: "External Partner", label: "External Partner" },
            ]}
          />
        </Grid>

        <Grid size={{ xs: 12, md: 6 }}>
          <Tooltip placement="top" title="Long name of the entity">
            <span className="field-tooltip-target">
              <FormField
                name="longName"
                label="Long Name"
                control={control}
                placeholder="Enter long name"
                required="Entity long name is mandatory !"
                onBlur={handleDuplicateLongName}
                helperText={longNameFound ? "Entity already exists" : undefined}
                error={longNameFound || undefined}
              />
            </span>
          </Tooltip>
        </Grid>

        <Grid size={{ xs: 12, md: 6 }}>
          <FormField
            name="shortName"
            label="Short Name"
            control={control}
            placeholder="Enter short name"
            required="Entity short name is mandatory !"
            onChange={(e) => {
              handleSlash(e);
            }}
            onBlur={handleDuplicateName}
            helperText={
              slashFound
                ? "Please remove '/' from the Short Name"
                : nameFound
                ? "Entity already exists"
                : undefined
            }
          />
        </Grid>

        <Grid size={{ xs: 12, md: 6 }}>
          <FormField
            name="entityStatus"
            label="Status"
            control={control}
            placeholder="auto-generated by system"
            disabled
          />
        </Grid>

        <Grid size={{ xs: 12, md: 6 }}>
          <Tooltip placement="top" title="Website URL of the data publisher">
            <span className="field-tooltip-target">
              <FormField
                name="website"
                label="Website"
                control={control}
                placeholder="Enter the Website as www.abc.com"
                rules={{
                  pattern: {
                    value: websitePattern,
                    message: "Enter a valid website !",
                  },
                }}
                startAdornment={
                  <InputAdornment position="start">{URL_PREFIX}</InputAdornment>
                }
              />
            </span>
          </Tooltip>
        </Grid>

        <Grid size={12}>
          <Tooltip placement="top" title="Entity Description">
            <span className="field-tooltip-target">
              <FormField
                name="entityDescription"
                label="Description"
                control={control}
                type="textarea"
                rows={4}
                placeholder="A description about the entity (Max 250 characters)"
                inputProps={{ maxLength: 250 }}
                required="Entity description is mandatory !"
              />
            </span>
          </Tooltip>
        </Grid>
      </Grid>
    </Box>
  );
};

const mapStateToProps = (state) => ({
  vendorList: state.vendor && state.vendor.list,
});

export default connect(mapStateToProps)(NewVendorForm);
