import React from "react";
import { screen } from "@testing-library/react";
import { useForm } from "react-hook-form";

import { renderWithProviders } from "../../utils/renderWithProviders";
import NewVendorForm from "../../../components/vendors/AddVendor/NewVendorForm";

// resetMocks is ON in this repo, so mock implementations are declared as plain
// functions inside the factory (they survive the per-test reset).
jest.mock("react-redux", () => ({
  ...jest.requireActual("react-redux"),
  useSelector: (cb) => cb({ vendor: { list: [] } }),
  useDispatch: () => jest.fn(),
  connect: () => (Component) => Component,
}));

const mockHandleNameCheck = jest.fn(() => false);
const mockHandleLongNameCheck = jest.fn(() => false);

// NewVendorForm relies on react-hook-form's `control` (via the design-system
// FormField). Render it through a tiny wrapper that owns the form context.
const FormHarness = (props) => {
  const { control, watch, setValue } = useForm({
    defaultValues: {
      entityId: "",
      entityType: "",
      longName: "",
      shortName: "",
      entityStatus: "",
      website: "",
      entityDescription: "",
    },
  });
  return (
    <NewVendorForm
      control={control}
      watch={watch}
      setValue={setValue}
      handleNameCheck={mockHandleNameCheck}
      handleLongNameCheck={mockHandleLongNameCheck}
      {...props}
    />
  );
};

const renderForm = (props) => renderWithProviders(<FormHarness {...props} />);

describe("NewVendorForm", () => {
  it("should render without crashing", () => {
    const { container } = renderForm();
    expect(container.querySelector(".MuiBox-root")).toBeInTheDocument();
  });

  it("should render the Entity ID field (label appears for the outlined input)", () => {
    renderForm();
    expect(screen.getAllByText("Entity ID").length).toBeGreaterThan(0);
  });

  it("should render the Entity Type select", () => {
    renderForm();
    expect(screen.getAllByText("Entity Type").length).toBeGreaterThan(0);
  });

  it("should render Long Name, Short Name, Status, Website and Description labels", () => {
    renderForm();
    expect(screen.getAllByText("Long Name").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Short Name").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Status").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Website").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Description").length).toBeGreaterThan(0);
  });

  it("should render the field placeholders", () => {
    renderForm();
    expect(
      screen.getByPlaceholderText(
        "EntityID will be generated by the system after the submission"
      )
    ).toBeInTheDocument();
    expect(screen.getByPlaceholderText("Enter long name")).toBeInTheDocument();
    expect(screen.getByPlaceholderText("Enter short name")).toBeInTheDocument();
    expect(
      screen.getByPlaceholderText("auto-generated by system")
    ).toBeInTheDocument();
    expect(
      screen.getByPlaceholderText("Enter the Website as www.abc.com")
    ).toBeInTheDocument();
    expect(
      screen.getByPlaceholderText(
        "A description about the entity (Max 250 characters)"
      )
    ).toBeInTheDocument();
  });

  it("should render the Entity ID field as disabled", () => {
    const { container } = renderForm();
    const entityIdInput = container.querySelector("#EntityId");
    expect(entityIdInput).toBeInTheDocument();
    expect(entityIdInput).toBeDisabled();
  });

  it("should render the Status field as disabled", () => {
    renderForm();
    const statusInput = screen.getByPlaceholderText("auto-generated by system");
    expect(statusInput).toBeDisabled();
  });

  it("should render the https:// website adornment", () => {
    renderForm();
    expect(screen.getByText("https://")).toBeInTheDocument();
  });
});
