import { createRef, useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useLocation } from "react-router-dom";
import { Col, Form, Input, Row, Select, Tooltip } from "antd";
import { formDataFn } from "../../store/actions/datafeedAction";
import { bindData } from "../addContract/bindData";
import { QuestionCircleOutlined } from "@ant-design/icons";
import "./DatafeedDetails.css";

const { Option } = Select;
const { TextArea } = Input;

const DatafeedDetails = (props) => {
  const [nameFound, setNameFound] = useState(false);
  const [longNameFound, setLongNameFound] = useState(false);
  const formRef = createRef();
  const dispatch = useDispatch();
  const location = useLocation();
  const layout = {
    labelCol: {
      span: 6,
    },
    wrapperCol: {
      span: 18,
    },
  };
  const data = useSelector((state) => state.datafeedInfo.formData);
  const datafeedsInfo = useSelector(
    (infoState) => infoState.datafeedInfo.datafeedsData
  );
  const onFinish = (values) => {
    if (!nameFound && !longNameFound) {
      dispatch(formDataFn(values));
      props.next(true);
    }
  };
  useEffect(() => {
    if (props.formData) {
      formRef.current.submit();
      props.next(false);
    }
  }, [props.formData]);

  useEffect(() => {
    if (data && Object.keys(data).length > 1) {
      const revisedData = ({
        documentationLink: url,
        feedDescription: description,
        feedId: datafeedId,
        feedStatus: status,
        personalData: personalDataType,
        ...rest
      }) => ({
        url,
        description,
        datafeedId,
        status,
        personalDataType,
        ...rest,
      });
      bindData([revisedData(data)], formRef.current);
    } else {
      formRef.current.setFieldsValue({
        status: "Pending",
      });
    }
  }, [data]);

  const handleNameCheck = (e, name) => {
    let inputValue = e.target.value;
    inputValue = inputValue.trim();
    if (datafeedsInfo && datafeedsInfo.length) {
      const datasetID = location.state.dataset.datasetId;
      const filterFeeds = datafeedsInfo.filter(
        (v) => v.datasetId === datasetID
      );
      let sName =
        data && Object.keys(data).length && data.feedId ? data[name] : null;
      const result = filterFeeds.some((v) => {
        let shName = v[name].trim();
        sName = sName && sName.trim();
        return shName === inputValue && sName !== inputValue;
      });
      return result;
    } else {
      return false;
    }
  };
  const toolTip = (val = "") => {
    const text = val.includes("Dataset")
      ? "The dataset that this feed is under."
      : "The type of personal data this feed contains.";
    return (
      <>
        {val}
        <Tooltip title={text}>
          <span style={{ color: "#007AFF" }}>
            <QuestionCircleOutlined /> 
          </span>
        </Tooltip>
      </>
    );
  };
  return (
    <div id="main">
      <Form {...layout} name="br-one" ref={formRef} onFinish={onFinish}>
        <Row gutter={[78, 0]}>
          <Col span={12}>
            <Form.Item name="datafeedId" label="Data Feed ID">
              <Input
                placeholder="Auto-generated by system"
                name="datafeedId"
                type="text"
                disabled={true}
              />
            </Form.Item>
          </Col>
          <Col span={12}>
            <Form.Item name="status" label="Status">
              <Input
                placeholder="Auto-generated by system"
                name="status"
                type="text"
                disabled={true}
              />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={[78, 0]}>
          <Col span={12}>
            <Form.Item
              id="dataSetNames"
              name="dataSetName"
              label={toolTip("Dataset Short Name ")}
            >
              <Input
                placeholder="Dataset Short Name"
                name="dataSetName"
                type="text"
                disabled={true}
              />
            </Form.Item>
          </Col>
          <Col span={12}>
            <Form.Item
              name="dataConfidentiality"
              label="Data Confidentiality"
              rules={[
                {
                  required: true,
                  message: "Data confidentiality is mandatory !",
                },
              ]}
            >
              <Select defaultValue="Select" name="dataConfidentiality">
                <Option value="Public">Public</Option>
                <Option value="Internal">Internal</Option>
                <Option value="Confidential">Confidential</Option>
                <Option value="Restricted">Restricted</Option>
              </Select>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={[78, 0]}>
          <Col span={12}>
            <Form.Item
              name="longName"
              label="Long Name"
              rules={[{ required: true, message: "Long name is mandatory !" }]}
              {...(longNameFound && {
                hasFeedback: true,
                help: longNameFound
                  ? "Data Feed long name already exists under this DataSet"
                  : "",
                validateStatus: longNameFound === false ? "success" : "error",
              })}
            >
              <Input
                placeholder="Long Name"
                name="longName"
                type="text"
                onBlur={(e) => setLongNameFound(handleNameCheck(e, "longName"))}
              />
            </Form.Item>
          </Col>
          <Col span={12}>
            <Form.Item
              id="personalDataTypes"
              name="personalDataType"
              label={toolTip("Personal Data Type")}
              rules={[ 
                {
                  required: true,
                  message: "Personal data type is mandatory !",
                },
              ]}
            >
              <Select defaultValue="Select" name="personalDataType">
                <Option value="Non-personal data">Non-personal data</Option>
                <Option value="Non-sensitive personal data">
                  Non-sensitive personal data
                </Option>
                <Option value="Sensitive personal data">
                  Sensitive personal data
                </Option>
              </Select>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={[78, 0]}>
          <Col className="gutter-row" span={12}>
            <Form.Item
              name="shortName"
              label="Short Name"
              rules={[{ required: true, message: "Short name is mandatory !" }]}
              {...(nameFound && {
                hasFeedback: true,
                help: nameFound
                  ? "Data Feed short name already exists under this DataSet"
                  : "",
                validateStatus: nameFound === false ? "success" : "error",
              })}
            >
              <Input
                placeholder="Short Name"
                name="shortName"
                type="text"
                onBlur={(e) => setNameFound(handleNameCheck(e, "shortName"))}
              />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={[78, 0]}>
          <Col className="gutter-row" span={12}>
            <Form.Item
              label="Description"
              name="description"
              rules={[
                { required: true, message: "Description is mandatory !" },
              ]}
            >
              <TextArea
                rows={4}
                maxLength={1000}
                showCount
                placeholder="A description about the Data Feed(Max 1000 characters)"
                name="description"
              />
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </div>
  );
};

export default DatafeedDetails;