import { useEffect, useState, memo } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useLocation } from "react-router-dom";
import { useForm } from "react-hook-form";
import { Box, Grid, Tooltip } from "@mui/material";
import { HelpOutlineOutlined as QuestionCircleOutlined } from "@mui/icons-material";

import { FormField } from "../../design-system";
import { formDataFn } from "../../store/actions/datafeedAction";
import "./DatafeedDetails.css";

const DATA_CONFIDENTIALITY_OPTIONS = [
  { value: "Public", label: "Public" },
  { value: "Internal", label: "Internal" },
  { value: "Confidential", label: "Confidential" },
  { value: "Restricted", label: "Restricted" },
];

const PERSONAL_DATA_OPTIONS = [
  { value: "Non-personal data", label: "Non-personal data" },
  { value: "Non-sensitive personal data", label: "Non-sensitive personal data" },
  { value: "Sensitive personal data", label: "Sensitive personal data" },
];

const DatafeedDetails = (props) => {
  const [nameFound, setNameFound] = useState(false);
  const [longNameFound, setLongNameFound] = useState(false);
  const dispatch = useDispatch();
  const location = useLocation();
  const data = useSelector((state) => state.datafeedInfo.formData);
  const datafeedsInfo = useSelector(
    (infoState) => infoState.datafeedInfo.datafeedsData
  );

  const { control, getValues, reset, setValue, trigger, setError, clearErrors } =
    useForm({
      defaultValues: {
        datafeedId: "",
        status: "",
        dataSetName: "",
        dataConfidentiality: "",
        longName: "",
        personalDataType: "",
        shortName: "",
        description: "",
      },
      mode: "onChange",
    });

  // Bind existing data in edit / navigate-back scenarios, otherwise seed the
  // status field with "Pending" (mirrors the original antd form behaviour).
  useEffect(() => {
    if (data && Object.keys(data).length > 1) {
      reset({
        datafeedId: data.feedId || "",
        status: data.feedStatus || "",
        dataSetName: data.dataSetName || "",
        dataConfidentiality: data.dataConfidentiality || "",
        longName: data.longName || "",
        personalDataType: data.personalData || "",
        shortName: data.shortName || "",
        description: data.feedDescription || "",
      });
    } else {
      setValue("status", "Pending");
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data]);

  // The parent flips `formData` to true when Next is clicked. Validate, and on
  // success persist + advance to the next step.
  useEffect(() => {
    if (props.formData) {
      trigger().then((ok) => {
        if (ok && !nameFound && !longNameFound) {
          dispatch(formDataFn(getValues()));
          props.next(true);
        }
      });
      props.next(false);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.formData]);

  const handleNameCheck = (e, name) => {
    let inputValue = e.target.value;
    inputValue = inputValue.trim();
    if (datafeedsInfo && datafeedsInfo.length) {
      const datasetID = location.state.dataset.datasetId;
      const filterFeeds = datafeedsInfo.filter(
        (v) => v.datasetId === datasetID
      );
      let sName =
        data && Object.keys(data).length && data.feedId ? data[name] : null;
      const result = filterFeeds.some((v) => {
        let shName = v[name].trim();
        sName = sName && sName.trim();
        return shName === inputValue && sName !== inputValue;
      });
      return result;
    } else {
      return false;
    }
  };

  const handleLongNameBlur = (e) => {
    const found = handleNameCheck(e, "longName");
    setLongNameFound(found);
    if (found) {
      setError("longName", {
        type: "manual",
        message: "Data Feed long name already exists under this DataSet",
      });
    } else {
      clearErrors("longName");
    }
  };

  const handleShortNameBlur = (e) => {
    const found = handleNameCheck(e, "shortName");
    setNameFound(found);
    if (found) {
      setError("shortName", {
        type: "manual",
        message: "Data Feed short name already exists under this DataSet",
      });
    } else {
      clearErrors("shortName");
    }
  };

  const toolTip = (val = "") => {
    const text = val.includes("Dataset")
      ? "The dataset that this feed is under."
      : "The type of personal data this feed contains.";
    return (
      <>
        {val}
        <Tooltip title={text}>
          <span style={{ color: "var(--color-primary)" }}>
            <QuestionCircleOutlined fontSize="inherit" />
          </span>
        </Tooltip>
      </>
    );
  };

  return (
    <div id="main">
      <Box>
        <Grid container spacing={3}>
          <Grid size={{ xs: 12, md: 6 }}>
            <FormField
              name="datafeedId"
              label="Data Feed ID"
              control={control}
              placeholder="Auto-generated by system"
              disabled
            />
          </Grid>
          <Grid size={{ xs: 12, md: 6 }}>
            <FormField
              name="status"
              label="Status"
              control={control}
              placeholder="Auto-generated by system"
              disabled
            />
          </Grid>

          <Grid size={{ xs: 12, md: 6 }}>
            <FormField
              name="dataSetName"
              label={toolTip("Dataset Short Name ")}
              control={control}
              placeholder="Dataset Short Name"
              disabled
            />
          </Grid>
          <Grid size={{ xs: 12, md: 6 }}>
            <FormField
              name="dataConfidentiality"
              label="Data Confidentiality"
              type="select"
              control={control}
              required="Data confidentiality is mandatory !"
              options={DATA_CONFIDENTIALITY_OPTIONS}
            />
          </Grid>

          <Grid size={{ xs: 12, md: 6 }}>
            <FormField
              name="longName"
              label="Long Name"
              control={control}
              placeholder="Long Name"
              required="Long name is mandatory !"
              onBlur={handleLongNameBlur}
            />
          </Grid>
          <Grid size={{ xs: 12, md: 6 }}>
            <FormField
              name="personalDataType"
              label={toolTip("Personal Data Type")}
              type="select"
              control={control}
              required="Personal data type is mandatory !"
              options={PERSONAL_DATA_OPTIONS}
            />
          </Grid>

          <Grid size={{ xs: 12, md: 6 }}>
            <FormField
              name="shortName"
              label="Short Name"
              control={control}
              placeholder="Short Name"
              required="Short name is mandatory !"
              onBlur={handleShortNameBlur}
            />
          </Grid>

          <Grid size={{ xs: 12, md: 6 }}>
            <FormField
              name="description"
              label="Description"
              type="textarea"
              rows={4}
              control={control}
              required="Description is mandatory !"
              placeholder="A description about the Data Feed(Max 1000 characters)"
              inputProps={{ maxLength: 1000 }}
            />
          </Grid>
        </Grid>
      </Box>
    </div>
  );
};

export default memo(DatafeedDetails);
