import { useEffect, useMemo, useState, memo } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useLocation } from "react-router-dom";
import { useForm } from "react-hook-form";
import { Box, Grid } from "@mui/material";
import { FormField } from "../../design-system";
import { datasetInfo } from "../../store/actions/datasetFormActions";
import { bindData } from "../addContract/bindData";

const DatasetDetails = (props) => {
  const [nameFound, setNameFound] = useState(false);
  const [longNameFound, setLongNameFound] = useState(false);

  const dispatch = useDispatch();
  const location = useLocation();
  const data = useSelector((state) => state.dataset.formData);
  const datasetsInfo = useSelector((state) => state.dataset.datasetInfo);

  const { control, setValue, getValues, reset, trigger, setError, clearErrors } =
    useForm({
      defaultValues: {
        datasetId: "",
        longName: "",
        shortName: "",
        status: "",
        description: "",
      },
      mode: "onChange",
    });

  // Adapter exposing the antd form API expected by the shared bindData helper.
  const formApi = useMemo(
    () => ({
      setFieldsValue: (obj) =>
        Object.keys(obj).forEach((k) => setValue(k, obj[k])),
      getFieldValue: (name) => getValues(name),
      getFieldsValue: () => getValues(),
      resetFields: () => reset(),
    }),
    [setValue, getValues, reset]
  );

  useEffect(() => {
    if (data && Object.keys(data).length) {
      const revisedData = ({
        datasetStatus: status,
        datasetDescription: description,
        ...rest
      }) => ({ status, description, ...rest });
      bindData([revisedData(data)], formApi);
    } else {
      formApi.setFieldsValue({
        status: "Active",
      });
    }
  }, [data, formApi]);

  const onFinish = (values) => {
    if (!nameFound && !longNameFound) {
      let finalValues = { ...values };
      if (location && location.state && location.state.isUpdate) {
        finalValues["entityId"] = data["entityId"];
        finalValues["licenseId"] = data["licenseId"];
      }
      dispatch(datasetInfo(finalValues));
      props.next(true);
    }
  };

  useEffect(() => {
    if (props.formData) {
      trigger().then((ok) => {
        if (ok) onFinish(getValues());
      });
      props.next(false);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.formData]);

  const handleNameCheck = (e) => {
    let inputValue = e.target.value;
    inputValue = inputValue.trim();
    if (datasetsInfo && datasetsInfo.length) {
      const licenseID = location.state.licence.licenseId;
      const filterFeeds = datasetsInfo.filter((v) => v.licenseId === licenseID);
      let sName =
        data && Object.keys(data).length && data.datasetId
          ? data.shortName
          : null;
      const result = filterFeeds.some((v) => {
        let shName = v.shortName;

        return shName === inputValue && sName !== inputValue;
      });

      return result;
    } else {
      return false;
    }
  };

  const handleLongNameCheck = (e) => {
    let inputValue = e.target.value;
    inputValue = inputValue.trim();

    if (datasetsInfo && datasetsInfo.length) {
      const licenseID = location.state.licence.licenseId;
      const filterFeeds = datasetsInfo.filter((v) => v.licenseId === licenseID);
      let lName =
        data && Object.keys(data).length && data.datasetId
          ? data.longName
          : null;
      const result = filterFeeds.some((v) => {
        let loName = v.longName;

        return loName === inputValue && lName !== inputValue;
      });

      return result;
    } else {
      return false;
    }
  };

  const onLongNameBlur = (e) => {
    const found = handleLongNameCheck(e);
    setLongNameFound(found);
    if (found) {
      setError("longName", {
        type: "manual",
        message: "Dataset name already exists under this Licence",
      });
    } else {
      clearErrors("longName");
    }
  };

  const onShortNameBlur = (e) => {
    const found = handleNameCheck(e);
    setNameFound(found);
    if (found) {
      setError("shortName", {
        type: "manual",
        message: "Dataset name already exists under this Licence",
      });
    } else {
      clearErrors("shortName");
    }
  };

  return (
    <div>
      <Box component="form" noValidate>
        <Grid container spacing={4}>
          <Grid size={{ xs: 12, md: 6 }}>
            <Box sx={{ mb: 2 }}>
              <FormField
                name="datasetId"
                label="Dataset ID"
                control={control}
                placeholder="Auto-generated by system"
                disabled
              />
            </Box>
            <Box sx={{ mb: 2 }}>
              <FormField
                name="longName"
                label="Long Name"
                control={control}
                placeholder="Long Name"
                required="Long name is mandatory !"
                onBlur={onLongNameBlur}
              />
            </Box>
            <Box sx={{ mb: 2 }}>
              <FormField
                name="shortName"
                label="Short Name"
                control={control}
                placeholder="Short Name"
                required="Short name is mandatory !"
                onBlur={onShortNameBlur}
              />
            </Box>
          </Grid>
          <Grid size={{ xs: 12, md: 6 }}>
            <Box sx={{ mb: 2 }}>
              <FormField
                name="status"
                label="Status"
                control={control}
                placeholder="Auto-generated by system"
                disabled
              />
            </Box>
            <Box sx={{ mb: 2 }}>
              <FormField
                name="description"
                label="Description"
                type="textarea"
                rows={4}
                control={control}
                required="Description is mandatory !"
                inputProps={{ maxLength: 1000 }}
                placeholder="A description about the dataset(Max 1000characters)"
              />
            </Box>
          </Grid>
        </Grid>
      </Box>
    </div>
  );
};

export default memo(DatasetDetails);
