import { createRef, useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useLocation } from "react-router-dom";
import { Col, Form, Input, Row, Select, Divider } from "antd";
import { datasetInfo } from "../../store/actions/datasetFormActions";
import { bindData } from "../addContract/bindData";

const { TextArea } = Input;

const DatasetDetails = (props) => {
  const [nameFound, setNameFound] = useState(false);

  const [longNameFound, setLongNameFound] = useState(false);
  const formRef = createRef();
  const dispatch = useDispatch();
  const location = useLocation();
  const data = useSelector((state) => state.dataset.formData);
  const datasetsInfo = useSelector((state) => state.dataset.datasetInfo);
  const layout = {
    labelCol: {
      span: 6,
    },
    wrapperCol: {
      span: 18,
    },
  };
  useEffect(() => {
    if (data && Object.keys(data).length) {
      const revisedData = ({
        datasetStatus: status,
        datasetDescription: description,
        ...rest
      }) => ({ status, description, ...rest });
      bindData([revisedData(data)], formRef.current);
    } else {
      formRef.current.setFieldsValue({
        status: "Active",
      });
    }
  }, [data]);
  useEffect(() => {
    if (props.formData) {
      formRef.current.submit();
      props.next(false);
    }
  }, [props.formData]);

  const onFinish = (values) => {
    if (!nameFound && !longNameFound) {
      let finalValues = { ...values };
      if (location && location.state && location.state.isUpdate) {
        finalValues["entityId"] = data["entityId"];
        finalValues["licenseId"] = data["licenseId"];
      }
      dispatch(datasetInfo(finalValues));
      props.next(true);
    }
  };

  const handleNameCheck = (e) => {
    let inputValue = e.target.value;
    inputValue = inputValue.trim();
    if (datasetsInfo && datasetsInfo.length) {
      const licenseID = location.state.licence.licenseId;
      const filterFeeds = datasetsInfo.filter((v) => v.licenseId === licenseID);
      let sName =
        data && Object.keys(data).length && data.datasetId
          ? data.shortName
          : null;
      const result = filterFeeds.some((v) => {
        let shName = v.shortName;

        return shName === inputValue && sName !== inputValue;
      });

      return result;
    } else {
      return false;
    }
  };

  const handleLongNameCheck = (e) => {
    let inputValue = e.target.value;
    inputValue = inputValue.trim();

    if (datasetsInfo && datasetsInfo.length) {
      const licenseID = location.state.licence.licenseId;
      const filterFeeds = datasetsInfo.filter((v) => v.licenseId === licenseID);
      let lName =
        data && Object.keys(data).length && data.datasetId
          ? data.longName
          : null;
      const result = filterFeeds.some((v) => {
        let loName = v.longName;

        return loName === inputValue && lName !== inputValue;
      });

      return result;
    } else {
      return false;
    }
  };

  return (
    <div>
      <Form {...layout} name="br-one" ref={formRef} onFinish={onFinish}>
        <Row gutter={[78, 0]}>
          <Col span={12}>
            <Col span={24}>
              <Form.Item name="datasetId" label="Dataset ID">
                <Input
                  placeholder="Auto-generated by system"
                  name="datasetId"
                  type="text"
                  disabled={true}
                />
              </Form.Item>
            </Col>
            <Col span={24}>
              <Form.Item
                name="longName"
                label="Long Name"
                rules={[
                  { required: true, message: "Long name is mandatory !" },
                ]}
                {...(longNameFound && {
                  hasFeedback: true,
                  help: longNameFound
                    ? "Dataset name already exists under this Licence"
                    : "",
                  validateStatus:
                    longNameFound.result === false ? "success" : "error",
                })}
              >
                <Input
                  placeholder="Long Name"
                  name="longName"
                  type="text"
                  onBlur={(e) => setLongNameFound(handleLongNameCheck(e))}
                />
              </Form.Item>
            </Col>
            <Col span={24}>
              <Form.Item
                name="shortName"
                label="Short Name"
                rules={[
                  { required: true, message: "Short name is mandatory !" },
                ]}
                {...(nameFound && {
                  hasFeedback: true,
                  help: nameFound
                    ? "Dataset name already exists under this Licence"
                    : "",
                  validateStatus:
                    nameFound.result === false ? "success" : "error",
                })}
              >
                <Input
                  placeholder="Short Name"
                  name="shortName"
                  type="text"
                  onBlur={(e) => setNameFound(handleNameCheck(e))}
                />
              </Form.Item>
            </Col>
          </Col>
          <Col span={12}>
            <Col span={24}>
              <Form.Item name="status" label="Status">
                <Input
                  placeholder="Auto-generated by system"
                  name="status"
                  type="text"
                  disabled={true}
                />
              </Form.Item>
            </Col>
            <Col span={24}>
              <Form.Item
                name="description"
                label="Description"
                rules={[
                  { required: true, message: "Description is mandatory !" },
                ]}
              >
                <TextArea
                  rows={4}
                  maxLength={1000}
                  showCount
                  placeholder="A description about the dataset(Max 1000characters)"
                  name="description"
                />
              </Form.Item>
            </Col>
          </Col>
        </Row>
      </Form>
    </div>
  );
};

export default DatasetDetails;