import { API_ADD_ROLE_URL, API_AGREEMENT_URL, API_AUTH_URL, API_DATAFLOW_URL, API_DATA_ENTITY_URL, API_EDP_PROD_URL, API_FOR_AGREEMENT, API_FOR_AUTH, API_FOR_CHANGE, API_FOR_DATAFLOW, API_FOR_ENTITLEMENT, API_FOR_ENTITY, API_FOR_SCHEMAS, API_FOR_SUBSCRIPTION, API_MS_ENTRA_CLIENT_ID, API_MS_ENTRA_CLIENT_ID_PROD, API_MS_ENTRA_URL, API_MS_ENTRA_URL_PROD, API_SCHEMAS_URL, API_SUBSCRIPTION_URL, API_TASKLIST_URL } from "./utils/Config";

let env = window.location.host;

// let env = "edp.global.standardchartered.com"


env = env.includes("localhost") ? "local" : env;

export const ENTRA_URL = env !== API_EDP_PROD_URL ? API_MS_ENTRA_URL : API_MS_ENTRA_URL_PROD;

export const CLIENT_ID = env !== API_EDP_PROD_URL ? API_MS_ENTRA_CLIENT_ID : API_MS_ENTRA_CLIENT_ID_PROD;

export const API_BASE_URL_FOR_ENTITY = env === "local" ? API_FOR_ENTITY : API_DATA_ENTITY_URL;
export const API_BASE_URL_FOR_AUTH = env === "local" ? API_FOR_AUTH : API_AUTH_URL;
export const API_BASE_URL_FOR_ENTITLEMENT = env === "local" ? API_FOR_ENTITLEMENT : API_ADD_ROLE_URL;
export const API_BASE_URL_FOR_DATAFLOW = env === "local" ? API_FOR_DATAFLOW : API_DATAFLOW_URL;
export const API_BASE_URL_FOR_AGREEMENT = env === "local" ? API_FOR_AGREEMENT : API_AGREEMENT_URL;
export const API_BASE_URL_FOR_SUBSCRIPTION = env === "local" ? API_FOR_SUBSCRIPTION : API_SUBSCRIPTION_URL;
export const API_BASE_URL_FOR_CHANGE = env === "local" ? API_FOR_CHANGE : API_TASKLIST_URL;
export const API_BASE_URL_FOR_SCHEMAS = env === "local" ? API_FOR_SCHEMAS : API_SCHEMAS_URL;